### ISSUE TITLE
`onp fcos` issue - No bootable disk

### ISSUE THREAD

**Issue by kevydotvinu** [kevydotvinu/openshift-network-playground#107]
- Correct `--disk=` option from `size=${DISK_GB}` to `${DISK}` in `virt-install` command.

**Comment by kevydotvinu** [comment]
- Add SSH password authentication
```
variant: fcos
version: 1.4.0
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes
```
